### PR TITLE
Alex/remove duplicate objs

### PR DESCRIPTION
**Pull request by AlB1111122**
## Summary

Move duplicated classes into a submodule made into a dependency. 

## NB clean build (run from root its fine inside a submodule)will not work anymore. as it deletes the shared objects jar. Make sure that the most recent SharedObjs its built```gradlew :SharedObjs:build``` and published ```gradlew :SharedObjs:publish```

If adding a class that will be used in multiple microservices, put it in SharedObjs.
## NB use the new ```./gradlew fullBuild``` in place of clean build due to ShareObjs needing to be built first. it runs ```gradlew clean  gradlew :SharedObjs:build gradlew :SharedObjs:publish gradlew build```

change the git actions to run fullBuild instead of build

### CODE REVIEW

**Review by oOoOoOo0o — APPROVED** [review]
Looks good. If you want you can add Lombok annotations to some of the DTOs to reduce the amount of code but other than that I tested every endpoint and it worked.
The only thing is auth's init.sql should have ```USE auth-service``` instead of just auth.

**Review by tadhgryan2012 — APPROVED** [review]
LGTM just fix the pipeline issue

**Review by oOoOoOo0o — APPROVED** [review]
Pipeline fixed

**Review by tadhgryan2012 — APPROVED** [review]
lgtm

**Pull request merged**
